name: libraryapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.3.0
  mobile_scanner: ^6.0.7
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_launcher_icons:
  android: true       # Use "launcher_icon" for the Android icon name
  ios: false           # Generate icons for iOS
  image_path: "assets/icon/icon.png" # Path to your master icon
   
